name: Docker Image CI

on:
  release:
      types: [published]
      
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - id: pre-step
      shell: bash
      run: echo "release-version=$(echo ${GITHUB_REF:10})" >> $GITHUB_OUTPUT
    - name: Publish Docker
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: koleos6/tydom2mqtt
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        tags: "latest,${{ steps.pre-step.outputs.release-version }}"
        registry: ghcr.io
            
